; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -relocation-model=pic < %s | FileCheck %s


define void @tail_memcpy(i8* %p, i8* %q, i32 %n) {
; CHECK-LABEL: tail_memcpy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    b memcpy
entry:
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %p, i8* %q, i32 %n, i1 false)
  ret void
}

define void @tail_memmove(i8* %p, i8* %q, i32 %n) {
; CHECK-LABEL: tail_memmove:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    b memmove
entry:
  tail call void @llvm.memmove.p0i8.p0i8.i32(i8* %p, i8* %q, i32 %n, i1 false)
  ret void
}

define void @tail_memset(i8* %p, i8 %c, i32 %n) {
; CHECK-LABEL: tail_memset:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    b memset
entry:
  tail call void @llvm.memset.p0i8.i32(i8* %p, i8 %c, i32 %n, i1 false)
  ret void
}

declare void @llvm.memcpy.p0i8.p0i8.i32(i8* nocapture, i8* nocapture readonly, i32, i1)
declare void @llvm.memmove.p0i8.p0i8.i32(i8* nocapture, i8* nocapture readonly, i32, i1)
declare void @llvm.memset.p0i8.i32(i8* nocapture, i8, i32, i1)

