// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1  -triple loongarch64-linux-gnu -emit-llvm %s -o - | FileCheck %s

typedef struct _B {
 static long ptr;
 int index;
} B;

typedef struct _A : B {
 float dd;
} A;

// CHECK-LABEL: @_Z3foov(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT__A:%.*]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast %struct._A* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, i64* [[TMP0]], align 4
// CHECK-NEXT:    ret i64 [[TMP1]]
//
A foo()
{
 A a;
 return a;
}

